genres = [
{text: 'romance anime and manga', size: 100},
{text: 'comedy anime and manga', size: 75},
{text: 'drama anime and manga', size: 55},
{text: 'historical fiction', size: 35},
{text: 'romance', size: 35},
{text: 'yuri', size: 30},
{text: 'LGBTI+ related media', size: 30},
{text: 'vampire fiction', size: 30},
{text: 'fantasy', size: 30},
{text: 'Gakushu manga', size: 25},
{text: 'fantasy comics', size: 25},
{text: 'Xianxia', size: 25},
{text: 'comedy', size: 25},
{text: 'thriller', size: 25},
{text: 'drama fiction', size: 25},
{text: 'action comics', size: 25},
{text: 'adventure fiction', size: 25},
{text: 'romantic comedy', size: 20},
{text: 'Sunjeong manhwa', size: 20},
{text: 'horror fiction', size: 20},
{text: 'apocalyptic fiction', size: 20},
{text: 'magical girl', size: 20},
{text: 'television series based on a novel', size: 20},
{text: 'slice of life', size: 20},
{text: 'fantasy anime and manga', size: 20},
{text: 'action anime and manga', size: 20},
{text: 'speculative fiction', size: 20},
{text: 'crime fiction', size: 20},
{text: 'romantic fiction', size: 20},
{text: 'school anime and manga', size: 20},
{text: 'zombie fiction', size: 20},
{text: 'survival fiction', size: 20},
{text: 'supernatural fiction', size: 20},
{text: 'horror comics', size: 20},
{text: 'mystery fiction', size: 20},
{text: 'action fiction', size: 20}
];
